"""Emit a trackit `--mixin_config` file holding the grid overrides.

The stock framework resolves configs as `config/<method>/<config_name>/config.yaml`
with NO override flag, so a mixin file is the only supported way to vary a run
without touching the repo's config tree.

Usage:
    grid_make_mixin.py <out.yaml> key=value [key=value ...]

Accepted keys are mapped to their `run.runner.train....` dotted path below.
The mixin mechanism only *replaces existing* keys, so every path must already be
present in the base config (all of these are).
"""
from __future__ import annotations

import sys
from pathlib import Path

PATHS = {
    "max_updates": "run.runner.train.stage.max_updates",
    "warmup_updates": "run.runner.train.stage.warmup_updates",
    "t_initial_updates": "run.runner.train.optimization.lr_scheduler.override.t_initial_updates",
    "sched_warmup_updates": "run.runner.train.optimization.lr_scheduler.parameters.warmup_updates",
    "lr": "run.runner.train.optimization.optimizer.lr",
    "lr_min": "run.runner.train.optimization.lr_scheduler.parameters.lr_min",
    "global_batch_size": "run.data.train.global_batch_size",
    "samples_per_epoch": "run.data.train.sampler.samples_per_epoch",
    "grad_accumulation_steps": "run.runner.train.optimization.grad_accumulation_steps",
    "max_grad_norm": "run.runner.train.optimization.max_grad_norm",
    "lambda_diag": "run.runner.train.criteria.lambda_diag",
    "lambda_rec": "run.runner.train.criteria.lambda_rec",
    "lambda_gain": "run.runner.train.criteria.lambda_gain",
    "lambda_align": "run.runner.train.criteria.lambda_align",
    "lambda_pres": "run.runner.train.criteria.lambda_pres",
    "lambda_mem": "run.runner.train.criteria.lambda_mem",
    "lambda_gate": "run.runner.train.criteria.lambda_gate",
    "lambda_motion": "run.runner.train.criteria.lambda_motion",
    "w_track_corr": "run.runner.train.criteria.w_track_corr",
    "w_track_clean": "run.runner.train.criteria.w_track_clean",
    "diagnosis_alpha": "run.runner.train.criteria.diagnosis_alpha",
}

INT_KEYS = {"max_updates", "warmup_updates", "t_initial_updates",
            "sched_warmup_updates", "global_batch_size", "samples_per_epoch",
            "grad_accumulation_steps"}


def emit(key: str, raw: str) -> str:
    if key in INT_KEYS:
        return str(int(float(raw)))
    return f"{float(raw):.10g}"


def main() -> int:
    out = Path(sys.argv[1])
    # accept either separate argv entries or one comma-joined blob
    raw_edits = []
    for arg in sys.argv[2:]:
        raw_edits.extend(p for p in arg.split(",") if p.strip())

    lines = [f"# generated by grid_make_mixin.py", ""]
    unknown = []
    for kv in raw_edits:
        k, _, v = kv.partition("=")
        k, v = k.strip(), v.strip()
        if not k:
            continue
        if k not in PATHS:
            unknown.append(k)
            continue
        lines.append(f'- path: "{PATHS[k]}"')
        lines.append(f"  value: {emit(k, v)}")
    if unknown:
        print(f"ERROR unknown keys: {unknown}")
        return 2
    if len(lines) <= 2:
        print("ERROR no edits parsed")
        return 2
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"WROTE {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
